use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Pfic",
        extends: None,
        description: Some("Programmable Fast Interrupt Controller."),
        items: &[
            BlockItem {
                name: "isr1",
                description: Some("Interrupt Status Register."),
                array: None,
                byte_offset: 0x0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Isr1"),
                }),
            },
            BlockItem {
                name: "isr2",
                description: Some("Interrupt Status Register."),
                array: None,
                byte_offset: 0x4,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Isr2"),
                }),
            },
            BlockItem {
                name: "isr3",
                description: Some("Interrupt Status Register."),
                array: None,
                byte_offset: 0x8,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Isr3"),
                }),
            },
            BlockItem {
                name: "isr4",
                description: Some("Interrupt Status Register."),
                array: None,
                byte_offset: 0xc,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Isr4"),
                }),
            },
            BlockItem {
                name: "ipr1",
                description: Some("Interrupt Pending Register."),
                array: None,
                byte_offset: 0x20,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipr1"),
                }),
            },
            BlockItem {
                name: "ipr2",
                description: Some("Interrupt Pending Register."),
                array: None,
                byte_offset: 0x24,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipr2"),
                }),
            },
            BlockItem {
                name: "ipr3",
                description: Some("Interrupt Pending Register."),
                array: None,
                byte_offset: 0x28,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipr3"),
                }),
            },
            BlockItem {
                name: "ipr4",
                description: Some("Interrupt Pending Register."),
                array: None,
                byte_offset: 0x2c,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipr4"),
                }),
            },
            BlockItem {
                name: "ithresdr",
                description: Some("Interrupt Priority Register."),
                array: None,
                byte_offset: 0x40,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ithresdr"),
                }),
            },
            BlockItem {
                name: "cfgr",
                description: Some("Interrupt Config Register."),
                array: None,
                byte_offset: 0x48,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfgr"),
                }),
            },
            BlockItem {
                name: "gisr",
                description: Some("Interrupt Global Register."),
                array: None,
                byte_offset: 0x4c,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Gisr"),
                }),
            },
            BlockItem {
                name: "vtfidr",
                description: Some("ID Config Register."),
                array: None,
                byte_offset: 0x50,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Vtfidr"),
                }),
            },
            BlockItem {
                name: "vtfaddrr0",
                description: Some("Interrupt 0 address Register."),
                array: None,
                byte_offset: 0x60,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Vtfaddrr0"),
                }),
            },
            BlockItem {
                name: "vtfaddrr1",
                description: Some("Interrupt 1 address Register."),
                array: None,
                byte_offset: 0x64,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Vtfaddrr1"),
                }),
            },
            BlockItem {
                name: "vtfaddrr2",
                description: Some("Interrupt 2 address Register."),
                array: None,
                byte_offset: 0x68,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Vtfaddrr2"),
                }),
            },
            BlockItem {
                name: "vtfaddrr3",
                description: Some("Interrupt 3 address Register."),
                array: None,
                byte_offset: 0x6c,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Vtfaddrr3"),
                }),
            },
            BlockItem {
                name: "ienr1",
                description: Some("Interrupt Setting Register."),
                array: None,
                byte_offset: 0x100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ienr1"),
                }),
            },
            BlockItem {
                name: "ienr2",
                description: Some("Interrupt Setting Register."),
                array: None,
                byte_offset: 0x104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ienr2"),
                }),
            },
            BlockItem {
                name: "ienr3",
                description: Some("Interrupt Setting Register."),
                array: None,
                byte_offset: 0x108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ienr3"),
                }),
            },
            BlockItem {
                name: "ienr4",
                description: Some("Interrupt Setting Register."),
                array: None,
                byte_offset: 0x10c,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ienr4"),
                }),
            },
            BlockItem {
                name: "irer1",
                description: Some("Interrupt Clear Register."),
                array: None,
                byte_offset: 0x180,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Irer1"),
                }),
            },
            BlockItem {
                name: "irer2",
                description: Some("Interrupt Clear Register."),
                array: None,
                byte_offset: 0x184,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Irer2"),
                }),
            },
            BlockItem {
                name: "irer3",
                description: Some("Interrupt Clear Register."),
                array: None,
                byte_offset: 0x188,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Irer3"),
                }),
            },
            BlockItem {
                name: "irer4",
                description: Some("Interrupt Clear Register."),
                array: None,
                byte_offset: 0x18c,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Irer4"),
                }),
            },
            BlockItem {
                name: "ipsr1",
                description: Some("Interrupt Pending Register."),
                array: None,
                byte_offset: 0x200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ipsr1"),
                }),
            },
            BlockItem {
                name: "ipsr2",
                description: Some("Interrupt Pending Register."),
                array: None,
                byte_offset: 0x204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ipsr2"),
                }),
            },
            BlockItem {
                name: "ipsr3",
                description: Some("Interrupt Pending Register."),
                array: None,
                byte_offset: 0x208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ipsr3"),
                }),
            },
            BlockItem {
                name: "ipsr4",
                description: Some("Interrupt Pending Register."),
                array: None,
                byte_offset: 0x20c,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ipsr4"),
                }),
            },
            BlockItem {
                name: "iprr1",
                description: Some("Interrupt Pending Clear Register."),
                array: None,
                byte_offset: 0x280,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iprr1"),
                }),
            },
            BlockItem {
                name: "iprr2",
                description: Some("Interrupt Pending Clear Register."),
                array: None,
                byte_offset: 0x284,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iprr2"),
                }),
            },
            BlockItem {
                name: "iprr3",
                description: Some("Interrupt Pending Clear Register."),
                array: None,
                byte_offset: 0x288,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iprr3"),
                }),
            },
            BlockItem {
                name: "iprr4",
                description: Some("Interrupt Pending Clear Register."),
                array: None,
                byte_offset: 0x28c,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iprr4"),
                }),
            },
            BlockItem {
                name: "iactr1",
                description: Some("Interrupt ACTIVE Register."),
                array: None,
                byte_offset: 0x300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iactr1"),
                }),
            },
            BlockItem {
                name: "iactr2",
                description: Some("Interrupt ACTIVE Register."),
                array: None,
                byte_offset: 0x304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iactr2"),
                }),
            },
            BlockItem {
                name: "iactr3",
                description: Some("Interrupt ACTIVE Register."),
                array: None,
                byte_offset: 0x308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iactr3"),
                }),
            },
            BlockItem {
                name: "iactr4",
                description: Some("Interrupt ACTIVE Register."),
                array: None,
                byte_offset: 0x30c,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iactr4"),
                }),
            },
            BlockItem {
                name: "iprior",
                description: Some("Interrupt Priority Register."),
                array: Some(Array::Regular(RegularArray { len: 64, stride: 1 })),
                byte_offset: 0x400,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 8,
                    fieldset: None,
                }),
            },
            BlockItem {
                name: "sctlr",
                description: Some("System Control Register."),
                array: None,
                byte_offset: 0xd10,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Sctlr"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfgr",
            extends: None,
            description: Some("Interrupt Config Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "resetsys",
                    description: Some("RESETSYS."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keycode",
                    description: Some("KEYCODE."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: Some("Keycode"),
                },
            ],
        },
        FieldSet {
            name: "Gisr",
            extends: None,
            description: Some("Interrupt Global Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "neststa",
                    description: Some("NESTSTA."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "gactsta",
                    description: Some("GACTSTA."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "gpendsta",
                    description: Some("GPENDSTA."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Iactr1",
            extends: None,
            description: Some("Interrupt ACTIVE Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "iacts2_3",
                    description: Some("IACTS."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iacts12",
                    description: Some("IACTS."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iacts14",
                    description: Some("IACTS."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iacts16_31",
                    description: Some("IACTS."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Iactr2",
            extends: None,
            description: Some("Interrupt ACTIVE Register."),
            bit_size: 32,
            fields: &[Field {
                name: "iacts",
                description: Some("IACTS."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iactr3",
            extends: None,
            description: Some("Interrupt ACTIVE Register."),
            bit_size: 32,
            fields: &[Field {
                name: "iacts",
                description: Some("IACTS."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iactr4",
            extends: None,
            description: Some("Interrupt ACTIVE Register."),
            bit_size: 32,
            fields: &[Field {
                name: "iacts",
                description: Some("IACTS."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ienr1",
            extends: None,
            description: Some("Interrupt Setting Register."),
            bit_size: 32,
            fields: &[Field {
                name: "inten",
                description: Some("INTEN."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 20,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ienr2",
            extends: None,
            description: Some("Interrupt Setting Register."),
            bit_size: 32,
            fields: &[Field {
                name: "inten",
                description: Some("INTEN."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ienr3",
            extends: None,
            description: Some("Interrupt Setting Register."),
            bit_size: 32,
            fields: &[Field {
                name: "inten",
                description: Some("INTEN."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ienr4",
            extends: None,
            description: Some("Interrupt Setting Register."),
            bit_size: 32,
            fields: &[Field {
                name: "inten",
                description: Some("INTEN."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ipr1",
            extends: None,
            description: Some("Interrupt Pending Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "pendsta2_3",
                    description: Some("PENDSTA."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pendsta12_31",
                    description: Some("PENDSTA."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 20,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipr2",
            extends: None,
            description: Some("Interrupt Pending Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendsta",
                description: Some("PENDSTA."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ipr3",
            extends: None,
            description: Some("Interrupt Pending Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendsta",
                description: Some("PENDSTA."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ipr4",
            extends: None,
            description: Some("Interrupt Pending Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendsta",
                description: Some("PENDSTA."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iprr1",
            extends: None,
            description: Some("Interrupt Pending Clear Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "pendreset2_3",
                    description: Some("PENDRESET."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pendreset12",
                    description: Some("PENDRESET."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pendreset14",
                    description: Some("PENDRESET."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pendreset16_31",
                    description: Some("PENDRESET."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Iprr2",
            extends: None,
            description: Some("Interrupt Pending Clear Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendreset",
                description: Some("PENDRESET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iprr3",
            extends: None,
            description: Some("Interrupt Pending Clear Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendreset",
                description: Some("PENDRESET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Iprr4",
            extends: None,
            description: Some("Interrupt Pending Clear Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendreset",
                description: Some("PENDRESET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ipsr1",
            extends: None,
            description: Some("Interrupt Pending Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "pendset2_3",
                    description: Some("PENDSET."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pendset12_31",
                    description: Some("PENDSET."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 20,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipsr2",
            extends: None,
            description: Some("Interrupt Pending Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendset",
                description: Some("PENDSET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ipsr3",
            extends: None,
            description: Some("Interrupt Pending Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendset",
                description: Some("PENDSET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ipsr4",
            extends: None,
            description: Some("Interrupt Pending Register."),
            bit_size: 32,
            fields: &[Field {
                name: "pendset",
                description: Some("PENDSET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Irer1",
            extends: None,
            description: Some("Interrupt Clear Register."),
            bit_size: 32,
            fields: &[Field {
                name: "intrset",
                description: Some("INTRSET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 20,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Irer2",
            extends: None,
            description: Some("Interrupt Clear Register."),
            bit_size: 32,
            fields: &[Field {
                name: "intrset",
                description: Some("INTRSET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Irer3",
            extends: None,
            description: Some("Interrupt Clear Register."),
            bit_size: 32,
            fields: &[Field {
                name: "intrset",
                description: Some("INTRSET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Irer4",
            extends: None,
            description: Some("Interrupt Clear Register."),
            bit_size: 32,
            fields: &[Field {
                name: "intrset",
                description: Some("INTRSET."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Isr1",
            extends: None,
            description: Some("Interrupt Status Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "intensta2_3",
                    description: Some("Interrupt ID Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "intensta12_31",
                    description: Some("Interrupt ID Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 20,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Isr2",
            extends: None,
            description: Some("Interrupt Status Register."),
            bit_size: 32,
            fields: &[Field {
                name: "intensta",
                description: Some("Interrupt ID Status."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Isr3",
            extends: None,
            description: Some("Interrupt Status Register."),
            bit_size: 32,
            fields: &[Field {
                name: "intensta",
                description: Some("Interrupt ID Status."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Isr4",
            extends: None,
            description: Some("Interrupt Status Register."),
            bit_size: 32,
            fields: &[Field {
                name: "intensta",
                description: Some("Interrupt ID Status."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ithresdr",
            extends: None,
            description: Some("Interrupt Priority Register."),
            bit_size: 32,
            fields: &[Field {
                name: "threshold",
                description: Some("THRESHOLD."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Sctlr",
            extends: None,
            description: Some("System Control Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "sleeponexit",
                    description: Some("SLEEPONEXIT."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sleepdeep",
                    description: Some("SLEEPDEEP."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wfitowfe",
                    description: Some("WFITOWFE."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sevonpend",
                    description: Some("SEVONPEND."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "setevent",
                    description: Some("SETEVENT."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rsten",
                    description: Some("RSTEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sysreset",
                    description: Some("SYSRESET."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Vtfaddrr0",
            extends: None,
            description: Some("Interrupt 0 address Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "vtf0en",
                    description: Some("VTF0EN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "addr0",
                    description: Some("ADDR0."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 31,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Vtfaddrr1",
            extends: None,
            description: Some("Interrupt 1 address Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "vtf1en",
                    description: Some("VTF1EN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "addr1",
                    description: Some("ADDR1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 31,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Vtfaddrr2",
            extends: None,
            description: Some("Interrupt 2 address Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "vtf2en",
                    description: Some("VTF2EN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "addr2",
                    description: Some("ADDR2."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 31,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Vtfaddrr3",
            extends: None,
            description: Some("Interrupt 3 address Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "vtf3en",
                    description: Some("VTF3EN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "addr3",
                    description: Some("ADDR3."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 31,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Vtfidr",
            extends: None,
            description: Some("ID Config Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "vtfid0",
                    description: Some("VTFID0."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vtfid1",
                    description: Some("VTFID1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vtfid2",
                    description: Some("VTFID2."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vtfid3",
                    description: Some("VTFID3."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[Enum {
        name: "Keycode",
        description: None,
        bit_size: 16,
        variants: &[
            EnumVariant {
                name: "KEY2",
                description: Some("NMI and EXC key."),
                value: 48303,
            },
            EnumVariant {
                name: "KEY3",
                description: Some("System Reset key."),
                value: 48879,
            },
            EnumVariant {
                name: "KEY1",
                description: Some("HWSTK and NEST key."),
                value: 64005,
            },
        ],
    }],
};
